apiVersion: v1
kind: ConfigMap
metadata:
  name: config-domain
  namespace: knative-serving
data:
  yjgbg.me: ""
---
apiVersion: v1
data:
  domainTemplate: |-
    {{if eq "index" .Name -}}
      {{- .Namespace -}}
    {{else -}}
      {{- .Name}}.{{.Namespace -}}
    {{end -}}
    .{{.Domain}}
kind: ConfigMap
metadata:
  name: config-network
  namespace: knative-serving
