apiVersion: v1
kind: Namespace
metadata:
  name: hello
---
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: index
  namespace: hello
spec:
  template:
    spec:
      containers:
        - image: yjgbg/flutter-web-demo1:latest
          ports:
            - containerPort: 80
